# Generated by Django 4.2.7 on 2023-11-20 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bits_id', models.CharField(max_length=13)),
                ('mess', models.CharField(choices=[('SR', 'SR MESS'), ('MEERA', 'MEERA MESS'), ('KRISHNA', 'KG MESS'), ('GANDHI', 'KG MESS'), ('RANAPRATAP', 'RVA MESS'), ('ASHOK', 'RVA MESS'), ('VISHWAKARMA', 'RVA MESS'), ('RAM', 'RB MESS'), ('BUDH', 'RB MESS'), ('MALVIYA', 'MALVIYA MESS'), ('CV RAMAN', 'CV MESS'), ('SHANKAR', 'SV MESS'), ('VYAS', 'SV MESS')], default='SR', max_length=20)),
                ('suser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mess_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psrn_no', models.CharField(max_length=10)),
                ('muser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
