# Generated by Django 4.2.7 on 2023-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_student', '0002_alter_mess_profile_muser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='mess',
        ),
        migrations.AddField(
            model_name='student_profile',
            name='student_hostel',
            field=models.CharField(choices=[('SR Mess', 'SR'), ('MEERA Mess', 'MEERA'), ('KG Mess', 'KRISHNA'), ('KG Mess', 'GANDHI'), ('RVA Mess', 'RANAPRATAP'), ('RVA Mess', 'ASHOK'), ('RVA Mess', 'VISHWAKARMA'), ('RB Mess', 'RAM'), ('RB Mess', 'BUDH'), ('MALVIYA Mess', 'MALVIYA'), ('CV Mess', 'CV'), ('SV Mess', 'SHANKAR'), ('SHANKAR Mess', 'VYAS')], default='SR Mess', max_length=20),
        ),
    ]
