# Generated by Django 4.2.7 on 2023-11-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_student', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess_profile',
            name='psrn_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='bits_id',
            field=models.CharField(default='', max_length=13),
        ),
    ]
