# Generated by Django 4.2.7 on 2023-11-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_student', '0006_alter_mess_profile_psrn_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_pics/'),
        ),
    ]
