# Generated by Django 4.2.7 on 2023-11-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_student', '0007_alter_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='menu/')),
            ],
        ),
    ]
