# Generated by Django 4.2.7 on 2023-11-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_student', '0008_menufile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='menufile',
            old_name='excel_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_avg_rating',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_rating',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_rating_value',
        ),
    ]
