# Generated by Django 4.2.7 on 2023-11-26 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mess_student', '0009_ratings_rename_excel_file_menufile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
