# Generated by Django 4.2.7 on 2023-11-26 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess_student', '0011_ratings_avg_rating_ratings_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mess_student.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
