# Generated by Django 4.2.7 on 2023-11-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_student', '0013_alter_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
