# Generated by Django 4.2.7 on 2023-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_student', '0014_alter_ratings_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='item',
            name='item_avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
