# Generated by Django 4.2.7 on 2023-12-11 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess_student', '0015_remove_ratings_avg_rating_item_item_avg_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_attended', models.PositiveIntegerField(default=0)),
                ('dinner_attended', models.PositiveIntegerField(default=0)),
                ('lunch_attended', models.PositiveIntegerField(default=0)),
                ('billtotal', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
