# Generated by Django 4.2.7 on 2023-12-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_student', '0017_meal_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(default='  ', max_length=10),
        ),
    ]
