# Generated by Django 4.2.7 on 2023-12-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_student', '0020_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
