# Generated by Django 4.2.6 on 2023-10-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sastaAmazon', '0002_products_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item_image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
