# Generated by Django 4.2.6 on 2023-10-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sastaAmazon', '0003_alter_products_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
    ]
