# Generated by Django 4.2.6 on 2023-10-18 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sastaAmazon', '0004_products_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='item_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
