# Generated by Django 4.2.6 on 2023-10-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sastaAmazon', '0005_products_item_discount_alter_products_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'permissions': [('change_secretdata', 'Can change secret data')]},
        ),
        migrations.AlterField(
            model_name='products',
            name='item_image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
