# Generated by Django 4.2.6 on 2023-10-20 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sastaAmazon', '0006_alter_products_options_alter_products_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterField(
            model_name='products',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
